name: Maven Release Workflow

on:
  workflow_call:

permissions:
  contents: write
  packages: write
  
jobs:
  release:    
    strategy:
      matrix:
        java-version: [ 21 ]
        distribution: [ temurin ]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:          
            fetch-depth: 0
        - uses: actions/setup-java@v4.7.1
          with:
            java-version: ${{ matrix.java-version }}
            distribution: ${{ matrix.distribution }}
            cache: 'maven'
        - name: Setup User
          run: |
            echo "The github.actor value is: '${{ github.actor }}'"
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
        - name: release - prepare
          run: mvn -B -q -ntp release:prepare -P release
        - name: get release tag
          id: extract_tag # Assign an ID to reference outputs
          run: |
            RELEASE_TAG=$(grep '^scm.tag=' release.properties | cut -d'=' -f2)
            echo "release_tag=${RELEASE_TAG}" >> "$GITHUB_OUTPUT"
        - name: echo release tag 
          run: echo ${{ steps.extract_tag.outputs.release_tag }}
        - name: release - perform (publish)
          run: mvn -B -q -ntp release:perform -P release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        - name: Generate changelog
          id: changelog
          uses: metcalfc/changelog-generator@v4.6.2
          with:
            myToken: ${{ secrets.GITHUB_TOKEN }}
            fetch: false
            reverse: false
        - name: Filter changelog
          id: filter_changelog
          run: |
            set -o noglob
            log=$(cat << "EOF" | grep -v -E 'chore\(release\)' | tac
            ${{ steps.changelog.outputs.changelog }}
            EOF
            )
            log="${log//'%'/'%25'}"
            log="${log//$'\n'/'%0A'}"
            log="${log//$'\r'/'%0D'}"
            echo "changelog=$log" >> $GITHUB_OUTPUT
        - name: Create Release
          if: steps.changelog.outputs.changelog != ''
          uses: ncipollo/release-action@v1.16.0
          with:
            tag: ${{ steps.extract_tag.outputs.release_tag }}
            draft: false
            prerelease: false
            body: ${{ steps.filter_changelog.outputs.changelog }}
          
